### PR TITLE
fix(dango): safe account auth issues

### LINKED ISSUE #262: bug: voter authentication in Safe account
Given a Safe account, consider such a sequence of events:

1. the Safe starts with 3 members: alice, bob, charlie
2. prop 1 is created to remove alice from the member set
3. prop 2 is created
4. prop 1 is passed and executed; at this time, prop 2 is still voting
5. alice attempts to vote in prop 2

Since prop 2 was created when alice was still a member, she should be able to vote.

However, in `dango_auth::authenticate`, the contract determines whether alice can vote by checking whether alice's username is associated with the Safe account, which isn't, because they are already disassociated in step 4.

### PR DESCRIPTION
**Pull request by larry0x**
closes #262 #263

replaces #267

### CODE REVIEW

File: dango/account/safe/src/execute.rs [hunk 1]
```diff
@@ -39,18 +39,41 @@ pub fn authenticate(ctx: AuthCtx, tx: Tx) -> anyhow::Result<AuthResponse> {
...
+                    }
                 }
             },
-            _ => bail!("a Safe account can only execute itself"),
+            _ => bail!("the only action a Safe account can do is to execute itself"),
         }
     }
 
-    authenticate_tx(ctx, tx, None, Some(metadata))?;
+    verify_nonce_and_signature(ctx, tx, None, Some(metadata))?;
```
Comment (larry0x) [inline dango/account/safe/src/execute.rs:76]: This addresses #262

File: dango/account/safe/src/execute.rs [hunk 2]
```diff
@@ -62,6 +85,11 @@ pub fn receive(_ctx: MutableCtx) -> StdResult<Response> {
 
 #[cfg_attr(not(feature = "library"), grug::export)]
 pub fn execute(ctx: MutableCtx, msg: ExecuteMsg) -> anyhow::Result<Response> {
+    ensure!(
+        ctx.sender == ctx.contract,
+        "only the Safe account itself can execute itself"
+    );
```
Comment (larry0x) [inline dango/account/safe/src/execute.rs:91]: This addresses #263

File: dango/account/safe/src/execute.rs [hunk 3]
```diff
@@ -334,33 +361,6 @@ mod tests {
...
-                }
-                .to_json_value()
-                .unwrap(),
-                credential: Json::null(),
-            });
-
-            assert!(res.is_err_and(|err| err.to_string().contains(&format!(
-                "account {SAFE} isn't associated with user `{non_member}`"
-            ))));
-        }
```
Comment (larry0x) [inline dango/account/safe/src/execute.rs:362]: This test case is no longer relevant as the same scenario is already covered by the integration test (in dango-testing)

File: dango/auth/src/lib.rs [hunk 4]
```diff
@@ -66,6 +61,40 @@ pub fn authenticate_tx(
...
+///
+/// This is intended for the multi-signature (Safe) account, where we ensure the
+/// username is associated with the Safe _at the time a proposal was created_,
+/// instead of _now_.
+pub fn verify_nonce_and_signature(
+    ctx: AuthCtx,
+    tx: Tx,
+    maybe_factory: Option<Addr>,
+    maybe_metadata: Option<Metadata>,
+) -> anyhow::Result<()> {
```
Comment (larry0x) [inline dango/auth/src/lib.rs:80]: My solution to #263 is to split `authenticate_tx` into two functions.

Spot and Margin accounts use `authenticate_tx`. This function:

1. ensures signer username is associated with the sender account
2. ensures nonce is correct
3. ensures signature is valid

Then a new function `verify_nonce_and_signature` is used by Safe account. This function skips (1) and only does (2) and (3).

**Review by larry0x — COMMENTED** [review]
I also pretty much rewrote all the tests in `dango/testing/tests/safe.rs`
